@startuml
AbstractRefreshableApplicationContext -> AbstractXmlApplicationContext: loadBeanDefinitions
AbstractXmlApplicationContext->AbstractBeanDefinitionReader: loadBeanDefinitions
 AbstractBeanDefinitionReader->XmlBeanDefinitionReader :loadBeanDefinitions
 XmlBeanDefinitionReader->XmlBeanDefinitionReader :doLoadBeanDefinitions
XmlBeanDefinitionReader->XmlBeanDefinitionReader:registerBeanDefinitions
XmlBeanDefinitionReader->DefaultBeanDefinitionDocumentReader: registerBeanDefinitions
DefaultBeanDefinitionDocumentReader->DefaultBeanDefinitionDocumentReader :doRegisterBeanDefinitions
DefaultBeanDefinitionDocumentReader->DefaultBeanDefinitionDocumentReader:parseBeanDefinitions
DefaultBeanDefinitionDocumentReader->DefaultBeanDefinitionDocumentReader:parseDefaultElement
DefaultBeanDefinitionDocumentReader->DefaultBeanDefinitionDocumentReader :processBeanDefinition
DefaultBeanDefinitionDocumentReader->BeanDefinitionReaderUtils:registerBeanDefinition
BeanDefinitionReaderUtils->DefaultListableBeanFactory:registerBeanDefinition
@enduml